
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.29.30154.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\Emkave\\CLionProjects\\Gravity\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-hcyc7k"
      binary: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-hcyc7k"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-hcyc7k'
        
        Run Build Command(s): "D:/CLion 2023.3.4/bin/ninja/win/x64/ninja.exe" -v cmTC_2b5df
        [1/2] C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_2b5df.dir\\CMakeCXXCompilerABI.cpp.obj /FdCMakeFiles\\cmTC_2b5df.dir\\ /FS -c "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        [2/2] cmd.exe /C "cd . && "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_2b5df.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_2b5df.dir\\CMakeCXXCompilerABI.cpp.obj  /out:cmTC_2b5df.exe /implib:cmTC_2b5df.lib /pdb:cmTC_2b5df.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:38 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.29.30154.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:38 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\Emkave\\CLionProjects\\Gravity\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:38 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-4913fr"
      binary: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-4913fr"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/_deps/sfml-src/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-4913fr'
        
        Run Build Command(s): "D:/CLion 2023.3.4/bin/ninja/win/x64/ninja.exe" -v cmTC_49d67
        [1/2] C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_49d67.dir\\CMakeCCompilerABI.c.obj /FdCMakeFiles\\cmTC_49d67.dir\\ /FS -c "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        [2/2] cmd.exe /C "cd . && "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_49d67.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_49d67.dir\\CMakeCCompilerABI.c.obj  /out:cmTC_49d67.exe /implib:cmTC_49d67.lib /pdb:cmTC_49d67.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckTypeSize.cmake:250 (check_include_file)"
      - "cmake-build-debug/_deps/sfml-src/cmake/Config.cmake:10 (check_type_size)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:41 (include)"
    checks:
      - "Looking for sys/types.h"
    directories:
      source: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-taapji"
      binary: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-taapji"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/_deps/sfml-src/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "HAVE_SYS_TYPES_H"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-taapji'
        
        Run Build Command(s): "D:/CLion 2023.3.4/bin/ninja/win/x64/ninja.exe" -v cmTC_96f62
        [1/2] C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_96f62.dir\\CheckIncludeFile.c.obj /FdCMakeFiles\\cmTC_96f62.dir\\ /FS -c C:\\Users\\Emkave\\CLionProjects\\Gravity\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-taapji\\CheckIncludeFile.c
        [2/2] cmd.exe /C "cd . && "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_96f62.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_96f62.dir\\CheckIncludeFile.c.obj  /out:cmTC_96f62.exe /implib:cmTC_96f62.lib /pdb:cmTC_96f62.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckTypeSize.cmake:251 (check_include_file)"
      - "cmake-build-debug/_deps/sfml-src/cmake/Config.cmake:10 (check_type_size)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:41 (include)"
    checks:
      - "Looking for stdint.h"
    directories:
      source: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-lbcc5s"
      binary: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-lbcc5s"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/_deps/sfml-src/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "HAVE_STDINT_H"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-lbcc5s'
        
        Run Build Command(s): "D:/CLion 2023.3.4/bin/ninja/win/x64/ninja.exe" -v cmTC_36f6e
        [1/2] C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_36f6e.dir\\CheckIncludeFile.c.obj /FdCMakeFiles\\cmTC_36f6e.dir\\ /FS -c C:\\Users\\Emkave\\CLionProjects\\Gravity\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-lbcc5s\\CheckIncludeFile.c
        [2/2] cmd.exe /C "cd . && "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_36f6e.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_36f6e.dir\\CheckIncludeFile.c.obj  /out:cmTC_36f6e.exe /implib:cmTC_36f6e.lib /pdb:cmTC_36f6e.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckTypeSize.cmake:252 (check_include_file)"
      - "cmake-build-debug/_deps/sfml-src/cmake/Config.cmake:10 (check_type_size)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:41 (include)"
    checks:
      - "Looking for stddef.h"
    directories:
      source: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7f36i9"
      binary: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7f36i9"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/_deps/sfml-src/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "HAVE_STDDEF_H"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7f36i9'
        
        Run Build Command(s): "D:/CLion 2023.3.4/bin/ninja/win/x64/ninja.exe" -v cmTC_05348
        [1/2] C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_05348.dir\\CheckIncludeFile.c.obj /FdCMakeFiles\\cmTC_05348.dir\\ /FS -c C:\\Users\\Emkave\\CLionProjects\\Gravity\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-7f36i9\\CheckIncludeFile.c
        [2/2] cmd.exe /C "cd . && "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_05348.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_05348.dir\\CheckIncludeFile.c.obj  /out:cmTC_05348.exe /implib:cmTC_05348.lib /pdb:cmTC_05348.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckTypeSize.cmake:146 (try_compile)"
      - "D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CheckTypeSize.cmake:271 (__check_type_size_impl)"
      - "cmake-build-debug/_deps/sfml-src/cmake/Config.cmake:10 (check_type_size)"
      - "cmake-build-debug/_deps/sfml-src/CMakeLists.txt:41 (include)"
    checks:
      - "Check size of void*"
    directories:
      source: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cfkytt"
      binary: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cfkytt"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_OSX_SYSROOT: ""
      CMAKE_USER_MAKE_RULES_OVERRIDE: "C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/_deps/sfml-src/cmake/CompilerOptionsOverride.cmake"
    buildResult:
      variable: "HAVE_SIZEOF_VOID_PTR"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Emkave/CLionProjects/Gravity/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cfkytt'
        
        Run Build Command(s): "D:/CLion 2023.3.4/bin/ninja/win/x64/ninja.exe" -v cmTC_0e954
        [1/2] C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_0e954.dir\\SIZEOF_VOID_PTR.c.obj /FdCMakeFiles\\cmTC_0e954.dir\\ /FS -c C:\\Users\\Emkave\\CLionProjects\\Gravity\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-cfkytt\\SIZEOF_VOID_PTR.c
        [2/2] cmd.exe /C "cd . && "D:\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_0e954.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_0e954.dir\\SIZEOF_VOID_PTR.c.obj  /out:cmTC_0e954.exe /implib:cmTC_0e954.lib /pdb:cmTC_0e954.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
...
